# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817519af3b406b254e27c0880d6adab6eb3d6aeae8ab0b77539c5b2bf942734684c85223e68cbe7574d64a226995b94eea1e835daa8969a36b184b19436ec57f

test:
  secret_key_base: 14bb1a239c89a153c5f914139d25a2f48ac72470458f904b4c6fb168e07e7adb249d02dc96100cb2111a5130c0a7ae9cccea4ae4075b7210badcb15216a88801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
